IF OBJECT_ID('SqlDeployment') IS NULL
BEGIN
	CREATE TABLE SqlDeployment
	(
		ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_SqlDeployment PRIMARY KEY,
	--	ScriptID UNIQUEIDENTIFIER NOT NULL CONSTRAINT UQ_SqlDeployment__ScriptID UNIQUE,
		ScriptName VARCHAR(100) NOT NULL,
		ScriptTag VARCHAR(25) NOT NULL,
		ScriptRunDate DATETIME NOT NULL CONSTRAINT DF_SqlDeployment__RunDate DEFAULT(GETUTCDATE())
	);
END
